#!/bin/bash

GIT_DIR=${GIT_DIR-`git rev-parse --show-toplevel`}
VERSION_FILE="$GIT_DIR/exsclaim/version.py"
read -r -d '' VERSION <  "$VERSION_FILE"
VERSION=$(echo "$VERSION" | sed 's/version = //g' | sed 's/"//g')
if [[ "$VERSION" == *"b"* ]]; then
	SHORT_VERSION=$(echo "$VERSION" | cut -d'b' -f 1)
	BETA_NUMBER=$(echo "$VERSION" | cut -d'b' -f 2)
	BETA_NUMBER=$((BETA_NUMBER+1))
	VERSION="${SHORT_VERSION}b${BETA_NUMBER}"
	echo "version = \"$VERSION\"" > "$VERSION_FILE"
	sed -i "s/^version = .*$/version = \"$TEST\"/g" pyproject.toml
	git add "$VERSION_FILE"
	echo "Changed the version number to $VERSION."
fi
