services:
    python:
        build: .
        networks:
            - backend
            - frontend
        volumes:
            - /usr/src/app/exsclaim:/argonne/code/exsclaim2.0/exsclaim
            - /usr/src/app/query:/argonne/code/exsclaim2.0/query
#            - /usr/src/app/notebooks:/argonne/code/exsclaim2.0/notebooks

    postgresql:
        image: postgres:latest
        ports:
            - "6543:5432"
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=localpassword
            - POSTGRES_DB=exsclaim
            - POSTGRES_USER=django
        networks:
            backend:
                aliases:
                    - db

networks:
    backend:
    frontend: