name: exsclaim2

services:
    python:
        build:
            target: core
            args:
                - UID=${UID}
                - GID=${GID}
                - UNAME=${UNAME}
        image: exsclaim/core
        env_file: .env
        environment:
            - EXSCLAIM_OLLAMA_HOST=http://ollama:11434
            - EXSCLAIM_LLAMA_CPP_HOST=http://llama-cpp:8080
            - POSTGRES_HOST=db
            - YOLO_CONFIG_DIR=/exsclaim/yolo
            - EXSCLAIM_CHECKPOINTS=/opt/exsclaim/exsclaim/figures/checkpoints
            - EXSCLAIM_UNDETECTED_SUBFIGURES_PATH=/opt/exsclaim/training/undetected
            - EXSCLAIM_UNCLASSIFIED_SUBFIGURES_PATH=/opt/exsclaim/training/unclassified
            - EXSCLAIM_UNSCRAPED_HTML=/opt/exsclaim/output/failed_html
        volumes:
            - ./exsclaim:/usr/local/lib/python3.14/site-packages/exsclaim
            - ./:/opt/exsclaim
            - ./output:/exsclaim/results
            - ./logs:/exsclaim/logs
            - ./data:/exsclaim/data
            - ./yolo:/exsclaim/yolo
            - /etc/localtime:/etc/localtime:ro
            - ./hf:/home/exsclaim/.cache/huggingface
            - /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf:/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf:ro
        ports:
            - "127.0.0.1:3000:3000"
            - "127.0.0.1:8000:8000"
        links:
            - postgres:db
        command: ["exsclaim", "--initialize_db", "ui", "--blocking"]
        depends_on:
            postgres:
                condition: service_healthy
            ollama:
                condition: service_healthy
            llama-cpp:
                condition: service_healthy
        deploy:
            resources:
                reservations:
                    devices:
                        -  driver: nvidia
                           count: all
                           capabilities: [ gpu ]
        runtime: nvidia
        secrets:
            - db_password
            - orcid_client_id
            - orcid_client_secret

    llama-cpp:
#        image: ghcr.io/ggml-org/llama.cpp:full-cuda13
        image: ghcr.io/ggml-org/llama.cpp:server-cuda13 # No entrypoint needed if using server
        env_file: .env
#        environment:
#            - CUDA_VISIBLE_DEVICES=""
        volumes:
            - ./llama:/models
            - /etc/localtime:/etc/localtime:ro
#        entrypoint: /app/llama-server
        command: ["--host", "0.0.0.0", "--port", "8080", "--models-dir", "/models", "--no-ui",
                  "--models-preset", "/models/config.ini"]
        ports:
            - "127.0.0.1:8080:8080"
        deploy:
            resources:
                reservations:
                    devices:
                        -   driver: nvidia
                            count: all
                            capabilities: [ gpu ]
        runtime: nvidia

    ollama:
        build:
            dockerfile: Dockerfile.ollama
        image: exsclaim/ollama
        env_file: .env
        environment:
            - OLLAMA_MODELS=/opt/ollama
        volumes:
            - /usr/share/ollama/.ollama/models:/opt/ollama
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "127.0.0.1:11434:11434"
        deploy:
            resources:
                reservations:
                    devices:
                        -   driver: nvidia
                            count: all
                            capabilities: [ gpu ]
        runtime: nvidia

    pycharm:
        extends:
            service: python
        build:
            target: pycharm
        image: exsclaim/pycharm
        entrypoint: []
#        command: [ "python3" ]
        ports: !reset []
        depends_on: !reset []
        healthcheck: !reset
            test: ["CMD", "exit", "0"]
        secrets:
            - db_password

    jupyter:
        build:
            target: "jupyter"
        image: exsclaim/jupyter
        env_file: .env
        volumes:
            - ./exsclaim:/usr/local/lib/python3.13/site-packages/exsclaim
            - ./query:/opt/exsclaim/query
            - ./notebooks:/opt/exsclaim/notebooks
        ports:
            - "8888:8888"

    postgres:
        image: postgres:18-alpine
        env_file: .env
        ports:
            - "127.0.0.1:6543:5432"
        environment:
            - POSTGRES_PORT=5432
            - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
        volumes:
            - ./sql-data-2:/var/lib/postgresql:Z
            - /etc/localtime:/etc/localtime:ro
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 5432 && exit 0 || exit 1'"]
            interval: 6s
            timeout: 4s
            start_period: 6s
            retries: 6
        secrets:
            - db_password

    nginx:
        image: nginx:1.29.4-alpine
        volumes:
            - "./nginx:/etc/nginx/conf.d"
            - /etc/localtime:/etc/localtime:ro
        restart: "unless-stopped"
        healthcheck:
            test: ["CMD", "curl", "-fs", "http://localhost/", "||", "exit", "1"]
            retries: 8
            start_interval: 4s
            start_period: 6s
        ports:
            - "443:443"
            - "80:80"

    postgres-17:
        image: postgres:17-alpine
        env_file: .env
        ports:
            - "127.0.0.1:6544:5432"
        environment:
            - POSTGRES_PORT=5432
            - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
        volumes:
            - ./sql-data:/var/lib/postgresql/data:Z
            - /etc/localtime:/etc/localtime:ro
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 5432 && exit 0 || exit 1'"]
            interval: 6s
            timeout: 4s
            start_period: 6s
            retries: 6
        secrets:
            - db_password

secrets:
    db_password:
        file: ./secrets/exsclaim-psql.txt

    orcid_client_id:
        file: ./secrets/orcid_client_id

    orcid_client_secret:
        file: ./secrets/orcid_client_secret
