name: exsclaim2

services:
    base:
        build:
            dockerfile: Dockerfile.exsclaim
            args:
                - EXSCLAIM_GITHUB_REVISION=exsclaim2_for_spin
                - UID=${UID:-1000}
                - GID=${GID:-1000}
                - UNAME=${UNAME:-exsclaim}
        image: exsclaim/base
        env_file: .env

    python:
        build:
            target: "prod"
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
                - UNAME=${UNAME:-exsclaim}
        image: exsclaim/core
        env_file: .env
        environment:
            - NTFY_LINK=${NTFY_LINK}
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        networks:
            - backend
        volumes:
#            # This was added for when the exsclaim module was being edited while a container already existed.
#            # Can be removed if no work is being done to exsclaim since pip already locally installed it.
            - ./exsclaim:/usr/local/lib/python3.11/site-packages/exsclaim
            - ./query:/usr/src/app/query
            - ./output:/usr/src/app/output

    jupyter:
        build:
            target: "jupyter"
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
                - UNAME=${UNAME:-exsclaim}
        image: exsclaim/jupyter
        env_file: .env
        environment:
            - HF_TOKEN=${HF_TOKEN}
            - NTFY_LINK=${NTFY_LINK}
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        networks:
            - backend
        volumes:
            - ./exsclaim:/usr/local/lib/python3.11/site-packages/exsclaim
            - ./query:/usr/src/app/query
            - ./notebooks:/usr/src/app/notebooks
        ports:
            - "8888:8888"

    postgres:
        image: postgres:latest
        env_file:
            -   .env
        environment:
            - TZ=${TZ}
            - PGTZ=${TZ}
        expose:
            - "$POSTGRES_PORT"
        ports:
            - "6543:$POSTGRES_PORT"
        networks:
            backend:
                aliases:
                    - db
                    - postgresql
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - ./sql-data:/var/lib/postgresql/data:Z
        healthcheck:
            test: [ "CMD", "/usr/bin/pg_isready", "-d", "$POSTGRES_DB", "-U", "$POSTGRES_USER", "-p", "$POSTGRES_PORT" ]
            interval: 5s
            timeout: 60s
            retries: 12
            start_period: 10s

    api:
        restart: always
        env_file: .env
        environment:
            - DJANGO_SECRET_KEY=local
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        image: exsclaim/ui/django-api
        build:
            context: ./api
            args:
                ENV: dev
            target: prod
        command: >
            bash -c "./manage.py migrate &&
                 ./manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./api/apps:/code/apps
            - ./api/config:/code/config
            - ./api/docs:/code/docs
            - ./exsclaim:/usr/local/lib/python3.11/site-packages/exsclaim
        ports:
            - "8000:8000"
        networks:
            - frontend
            - backend
        depends_on:
            postgres:
                condition: service_healthy

    fastapi:
        restart: always
        env_file: .env
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        image: exsclaim/ui/api
        build:
            context: ./fastapi
            target: dev
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
                - UNAME=${UNAME:-exsclaim}
        volumes:
            - ./exsclaim:/usr/local/lib/python3.11/site-packages/exsclaim
            - ./fastapi/api:/usr/src/app/api
            - ./logs:/exsclaim/logs
            - ./output:/exsclaim/results
        ports:
            - "81:80"
        networks:
            frontend:
                aliases:
                    - api
            backend:
                aliases:
                    - api
        depends_on:
            postgres:
                condition: service_healthy

    dashboard:
        build:
            context: ./dashboard
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
                - UNAME=${UNAME:-exsclaim}
        env_file: .env
        image: exsclaim/ui/dashboard
        environment:
            - POSTGRES_PORT="${POSTGRES_PORT-5078}"
            - PORT=${FASTAPI_PORT}
        ports:
            - "3000:3000"
        networks:
            - frontend
            - backend
        volumes:
            - "./dashboard:/app"
        depends_on:
            fastapi:
                condition: service_healthy

networks:
    frontend:
    backend:

volumes:
    exsclaim_module:
        driver: local
        driver_opts:
            type: bind
            device: /usr/src/app/exsclaim

    notebooks:
        driver: local
        driver_opts:
            type: bind
            device: /usr/src/app/notebooks

    query:
        driver: local
        driver_opts:
            type: bind
            device: /usr/src/app/query
