name: exsclaim2

services:
    python:
        build:
            target: core
            args:
                - UID=${UID}
                - GID=${GID}
                - UNAME=${UNAME}
                - UV_DEFAULT_INDEX=${UV_DEFAULT_INDEX}
        image: exsclaim/core
        env_file: .env
        environment:
            - POSTGRES_HOST=db
            - YOLO_CONFIG_DIR=/exsclaim/yolo
            - EXSCLAIM_CHECKPOINTS=/opt/exsclaim/exsclaim/figures/checkpoints
        volumes:
            - ./exsclaim:/usr/local/lib/python3.13/site-packages/exsclaim
            - ./:/opt/exsclaim
            - ./output:/exsclaim/results
            - ./logs:/exsclaim/logs
            - /etc/localtime:/etc/localtime:ro
#            - /usr/share/ollama/.ollama/models:/opt/ollama
        ports:
            - "127.0.0.1:3000:3000"
            - "127.0.0.1:8000:8000"
            - "127.0.0.1:11434:11434"
        links:
            - postgres:db
        depends_on:
            postgres:
                condition: service_healthy
        deploy:
            resources:
                reservations:
                    devices:
                        -  driver: nvidia
                           count: all
                           capabilities: [ gpu ]
        runtime: nvidia
        secrets:
            - db_password

    pycharm:
        extends:
            service: python
        build:
            target: pycharm
        image: exsclaim/pycharm
        command: [ "python3" ]
#        ports: !reset []
        secrets:
            - db_password

    jupyter:
        build:
            target: "jupyter"
        image: exsclaim/jupyter
        env_file: .env
        volumes:
            - ./exsclaim:/usr/local/lib/python3.13/site-packages/exsclaim
            - ./query:/opt/exsclaim/query
            - ./notebooks:/opt/exsclaim/notebooks
        ports:
            - "8888:8888"

    postgres:
        image: postgres:17-alpine
        env_file: .env
        ports:
            - "127.0.0.1:6543:5432"
        environment:
            - POSTGRES_PORT=5432
            - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
        volumes:
            - ./sql-data:/var/lib/postgresql/data:Z
            - /etc/localtime:/etc/localtime:ro
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 5432 && exit 0 || exit 1'"]
            interval: 6s
            timeout: 4s
            start_period: 6s
            retries: 6
        secrets:
            - db_password


secrets:
    db_password:
        file: ./exsclaim-psql.txt
