#!/bin/bash

function api_failed() {
	echo "API Healthcheck failed: \"$1\"";
	exit 1;
}

function dashboard_failed() {
	echo "Dashboard Healthcheck failed: \"$1\"";
	exit 2;
}

RESPONSE=$(curl -fs "http://localhost:$FAST_API_PORT/healthcheck")
if [[ "$?" -ne 0 ]]; then
	api_failed "$RESPONSE"
fi

RESPONSE=$(curl -fs "http://localhost:$DASHBOARD_PORT/healthcheck")
if [[ "$?" -ne 0 ]]; then
	dashboard_failed "$RESPONSE"
fi

exit 0