services:
    python:
        build: .
        image: exsclaim/core
        env_file: .env
        environment:
            - HF_TOKEN=${HF_TOKEN}
            - NTFY_LINK=${NTFY_LINK}
        networks:
            - backend
            - frontend
        volumes:
#            - ./exsclaim:/usr/local/lib/python3.11/site-packages/exsclaim
            - ./query:/usr/src/app/query
            - ./notebooks:/usr/src/app/notebooks
        ports:
            - "8888:8888"

    # The service that is used to create a Python Interpreter in JetBrain's PyCharm Professional IDE
    pycharm:
        build: .
        env_file: .env
        environment:
            - HF_TOKEN=${HF_TOKEN}
            - NTFY_LINK=${NTFY_LINK}
        networks:
            - backend
            - frontend
        volumes:
            - type: bind
              source: ./exsclaim
              target: /usr/src/code/exsclaim
            - type: bind
              source: ./query
              target: /usr/src/app/query

    postgresql:
        image: postgres:latest
        ports:
            - "6543:5432"
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=localpassword
            - POSTGRES_DB=exsclaim
            - POSTGRES_USER=django
        networks:
            backend:
                aliases:
                    - db

networks:
    backend:
    frontend:

volumes:
    exsclaim_module:
        driver: local
        driver_opts:
            type: bind
            device: /usr/src/app/exsclaim

    notebooks:
        driver: local
        driver_opts:
            type: bind
            device: /usr/src/app/notebooks

    query:
        driver: local
        driver_opts:
            type: bind
            device: /usr/src/app/query