version: '3.8'

services:
    python:
        build: .
        ports:
            - "8888:8888"
        networks:
            - backend
            - frontend
        volumes:
            - type: bind
              source: ./exsclaim
              target: /usr/src/app/exsclaim

    postgresql:
        image: postgres:latest
        ports:
            - "6543:5432"
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=localpassword
            - POSTGRES_DB=exsclaim
            - POSTGRES_USER=django
        networks:
            backend:
                aliases:
                    - db
    jupyter:
        image: jupyter/datascience-notebook

networks:
    backend:
    frontend: