FROM ollama/ollama:0.30.10

ENV OLLAMA_HOST=0.0.0.0:11434

HEALTHCHECK --interval=60s --timeout=4s --start-period=12s --retries=8 CMD curl -fs http://localhost:11434/api/tags || exit 1

RUN apt update; \
    apt install -y --no-install-recommends curl gnupg; \
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg; \
	curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list \
    	| sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \
    	| tee /etc/apt/sources.list.d/nvidia-container-toolkit.list; \
    apt update; \
    apt install -y nvidia-container-toolkit; \
    apt clean; \
	rm -rf /var/lib/apt/lists/*;
