[project]
name = "exsclaim"
description = "EXSCLAIM! is a library for the automatic EXtraction, Separation, and Caption-based natural Language Annotation of IMages from scientific figures."
authors = [
    { name = "Eric Schwenker", email = "developer@materialeyes.org" },
    { name = "Trevor Spreadbury", email = "developer@materialeyes.org" },
    { name = "Weixin Jiang", email = "developer@materialeyes.org" },
    { name = "Maria Chan", email = "developer@materialeyes.org" },
]
maintainers = [
    { name = "Len Washington III", email = "developer@materialeyes.org" }
]
license-files = [ "LICENSE" ]
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Environment :: Web Environment",
    "Framework :: Dash",
    "Framework :: FastAPI",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: JavaScript",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Text Processing"
]
requires-python = ">=3.13.2"
dynamic = [
    "version",
]
dependencies = [
    # Image manipulation
    "numpy==2.5.2",
    "opencv-contrib-python-headless==5.0.0.93",
    "Pillow==12.3.0",
    "ultralytics==8.4.152",
    "pi_heif==1.4.0",

    # HTTP requests
    "httpx2==2.13.0",
    "brotli==1.2.0",
    "playwright==1.62.0",
    "playwright-stealth==2.0.3",
    "urllib3==2.7.0",
    "beautifulsoup4==4.15.0",
    "soupsieve==2.9.2",
    "tqdm==4.68.3",
    "curl-cffi==0.16.3",

    # Connecting to the PostgreSQL database
    "asyncpg==0.31.0",

    # Used with the Figure Separator
    "cairosvg==2.9.1",
    "pycocotools==2.0.11",

    "PyYAML==6.0.3",
    "pymupdf==1.28.2",

    "torch==2.14.0",
    "torchvision==0.29.0",
    "pytorch-model-summary==0.1.2",
    "datasets==5.0.0",

    # Run LLMs
    "openai==3.13.0",
    "asksageclient==1.42",

    # Used with the API
    "dash[async, compress]==4.4.1",
    "flask==3.1.3",
    "dash-extensions==2.0.6",
    "dash-ag-grid==35.3.0",
    "fastapi[standard]==0.141.1",
    "pydantic==2.13.5",
    "starlette==1.6.0",
    "uvicorn==0.53.0",
    "hypercorn==0.18.0",
    # "sqlmodel==0.0.42",
    "sqlmodel @ git+https://github.com/lwashington3/sqlmodel",
    "sqlalchemy==2.0.52",
    "pydantic_settings==2.15.0",
    "orjson==3.12.0",
    "pyjwt==2.14.0",
    "cryptography==50.0.1",

    "uuid-utils==0.17.0; python_version < '3.14'",

    # Used with the Dashboard
    "dash_bootstrap_components==2.0.4",
    "gunicorn[gevent]==26.2.0",
]

[project.optional-dependencies]
ollama = [
    "ollama~=0.6.2"
]

test = [
    "Faker==40.36.0",
    "pytest-asyncio==1.4.0",
    "deepdiff==8.6.2",
    "unidecode==1.4.0",
    "pytest-asyncio==1.4.0",
    "pytest-env==1.7.0"
]

dev = [
    "ipython==9.15.0",
    "pydevd==3.5.0",
    "pydevd_pycharm~=263.4732.31",
    "pytest==9.1.1",
    "scipy-stubs==1.18.0.0",
    "trio==0.33.0",
    "ruff==0.16.8",
    "alembic==1.20.0"
]

[project.urls]
Homepage = "https://exsclaim.materialeyes.org"
Source = "https://github.com/MaterialEyes/exsclaim2.0"
Documentation = "https://github.com/MaterialEyes/exsclaim2.0/wiki"
Issues = "https://github.com/MaterialEyes/exsclaim2.0/issues"
Paper = "https://arxiv.org/abs/2103.10631"
Changelog = "https://github.com/MaterialEyes/exsclaim2.0/blob/dev/CHANGELIST.md"

[project.scripts]
exsclaim = "exsclaim.__main__:main"

[build-system]
requires = ["setuptools>=83.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["exsclaim", "exsclaim.figures", "exsclaim.journals", "exsclaim.llms", "exsclaim.utilities", "exsclaim.api",
    "exsclaim.dashboard", "exsclaim.dashboard.components", "exsclaim.dashboard.pages"]
include-package-data = true

[tool.setuptools.dynamic]
version = { attr = "exsclaim.version.version" }

[tool.ruff]
line-length=127
target-version = "py314"

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["W191", "E501", "I001", "E101"]


[tool.alembic]
# path to migration scripts.
# this is typically a path given in POSIX (e.g. forward slashes)
# format, relative to the token %(here)s which refers to the location of this ini file
script_location = "%(here)s/exsclaim/alembic"

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
# see https://alembic.sqlalchemy.org/en/latest/tutorial.html#editing-the-ini-file for all available tokens
 file_template = "%%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s"

# additional paths to be prepended to sys.path. defaults to the current working directory.
prepend_sys_path = ["exsclaim"]

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the tzdata library which can be installed by adding
# `alembic[tz]` to the pip requirements.
# string value is passed to ZoneInfo()
# leave blank for localtime
# timezone =

# max length of characters to apply to the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# version location specification; This defaults
# to <script_location>/versions.  When using multiple version
# directories, initial revisions must be specified with --version-path.
# version_locations = [
#    "%(here)s/alembic/versions",
#    "%(here)s/foo/bar"
# ]


# set to 'true' to search source files recursively
# in each "version_locations" directory
# new in Alembic version 1.10
# recursive_version_locations = false

# the output encoding used when revision files
# are written from script.py.mako
# output_encoding = "utf-8"

# This section defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for further
# detail and examples
# [[tool.alembic.post_write_hooks]]
# format using "black" - use the console_scripts runner,
# against the "black" entrypoint
# name = "black"
# type = "console_scripts"
# entrypoint = "black"
# options = "-l 79 REVISION_SCRIPT_FILENAME"
#
# [[tool.alembic.post_write_hooks]]
# lint with attempts to fix using "ruff" - use the module runner, against the "ruff" module
# name = "ruff"
# type = "module"
# module = "ruff"
# options = "check --fix REVISION_SCRIPT_FILENAME"
#
# [[tool.alembic.post_write_hooks]]
# Alternatively, use the exec runner to execute a binary found on your PATH
# name = "ruff"
# type = "exec"
# executable = "ruff"
# options = "check --fix REVISION_SCRIPT_FILENAME"

