"""Alembic should be up to date with the autogenerated schema.

Revision ID: 3924f9a632d1
Revises: 645e11557c05
Create Date: 2026-09-18 14:15:19.252346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3924f9a632d1'
down_revision: Union[str, Sequence[str], None] = '645e11557c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.create_unique_constraint("public_banner_unique_id", ['id'])

    with op.batch_alter_table('classification_codes', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=False)

    with op.batch_alter_table('article', schema='results') as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('open',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('authors', schema='results') as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('authors_orcid_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_results_authors_id'), ['id'], unique=True)

    with op.batch_alter_table('figure', schema='results') as batch_op:
        batch_op.drop_constraint(batch_op.f('figure_run_id_articles_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key("figure_article_id_fkey", 'article', ['article_id'], ['id'], referent_schema='results', onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('runs', schema='results') as batch_op:
        batch_op.drop_index(batch_op.f('ix_results_id'))
        batch_op.drop_index(batch_op.f('ix_results_results_user_id_start_time'))
        batch_op.create_index('ix_results_runs_user_id_start_time', ['user_id', 'start_time'], unique=False)
        batch_op.create_unique_constraint("runs_id_key", ['id'])
        batch_op.drop_constraint(batch_op.f('results_user_id_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key("runs_user_id_users_id_fkey", 'users', ['user_id'], ['id'], referent_schema='users', onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('scale', schema='results') as batch_op:
        batch_op.drop_constraint(batch_op.f('scale_scale_bar_id_scale_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key("scale_run_id_subfigure_id_fkey", 'subfigure', ['run_id', 'subfigure_id'], ['run_id', 'id'], referent_schema='results', onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('scalelabel', schema='results') as batch_op:
        batch_op.drop_constraint(batch_op.f('scalelabel_scale_bar_id_scale_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key("scalelabel_run_id_scale_bar_id_scale_id_fkey", 'scale', ['run_id', 'scale_bar_id'], ['run_id', 'id'], referent_schema='results', onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('subfigure', schema='results') as batch_op:
        batch_op.alter_column('classification_code',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.CHAR(length=2),
               existing_nullable=False)

        batch_op.drop_constraint(batch_op.f('subfigure_classification_code_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('subfigure_figure_id_figure_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('subfigure_run_id_figure_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key("subfigure_run_id_runs_id_fkey", 'runs', ['run_id'], ['id'], referent_schema='results', onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key("subfigure_figure_id_figure_id_fkey", 'figure', ['figure_id'], ['id'], referent_schema='results', onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key("subfigure_classification_code_classification_codes_code_fkey", 'classification_codes', ['classification_code'], ['code'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('subfigurelabel', schema='results') as batch_op:
        batch_op.drop_constraint(batch_op.f('subfigurelabel_subfigure_id_subfigure_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key("subfigurelabel_subfigure_id_subfigure_id_fkey", 'subfigure', ['run_id', 'subfigure_id'], ['run_id', 'id'], referent_schema='results', onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('password_reset', schema='users') as batch_op:
        batch_op.create_unique_constraint("users_password_reset_email_unique", ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset', schema='users') as batch_op:
        batch_op.drop_constraint("users_password_reset_email_unique", type_='unique')

    with op.batch_alter_table('subfigurelabel', schema='results') as batch_op:
        batch_op.drop_constraint("subfigurelabel_subfigure_id_subfigure_id_fkey", type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subfigurelabel_subfigure_id_subfigure_id_fkey'), 'subfigure', ['run_id', 'subfigure_id'], ['run_id', 'id'], referent_schema='results')

    with op.batch_alter_table('subfigure', schema='results') as batch_op:
        batch_op.drop_constraint("subfigure_run_id_runs_id_fkey", type_='foreignkey')
        batch_op.drop_constraint("subfigure_figure_id_figure_id_fkey", type_='foreignkey')
        batch_op.drop_constraint("subfigure_classification_code_classification_codes_code_fkey", type_='foreignkey')

        batch_op.create_foreign_key(batch_op.f('subfigure_run_id_figure_id_fkey'), 'runs', ['run_id'], ['id'], referent_schema='results')
        batch_op.create_foreign_key(batch_op.f('subfigure_figure_id_figure_id_fkey'), 'figure', ['figure_id'], ['id'], referent_schema='results')
        batch_op.create_foreign_key(batch_op.f('subfigure_classification_code_fkey'), 'classification_codes', ['classification_code'], ['code'])

        batch_op.alter_column('classification_code',
               existing_type=sa.CHAR(length=2),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)

    with op.batch_alter_table('scalelabel', schema='results') as batch_op:
        batch_op.drop_constraint("scalelabel_run_id_scale_bar_id_scale_id_fkey", type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('scalelabel_scale_bar_id_scale_id_fkey'), 'scale', ['run_id', 'scale_bar_id'], ['run_id', 'id'], referent_schema='results')

    with op.batch_alter_table('scale', schema='results') as batch_op:
        batch_op.drop_constraint("scale_run_id_subfigure_id_fkey", type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('scale_scale_bar_id_scale_id_fkey'), 'subfigure', ['run_id', 'subfigure_id'], ['run_id', 'id'], referent_schema='results')

    with op.batch_alter_table('runs', schema='results') as batch_op:
        batch_op.drop_constraint("runs_user_id_users_id_fkey", type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('results_user_id_user_id_fkey'), 'users', ['user_id'], ['id'], referent_schema='users')
        batch_op.drop_constraint("runs_id_key", type_='unique')
        batch_op.drop_index('ix_results_runs_user_id_start_time')
        batch_op.create_index(batch_op.f('ix_results_results_user_id_start_time'), ['user_id', 'start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_id'), ['id'], unique=True)

    with op.batch_alter_table('figure', schema='results') as batch_op:
        batch_op.drop_constraint("figure_article_id_fkey", type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('figure_run_id_articles_id_fkey'), 'article', ['article_id'], ['id'], referent_schema='results')

    with op.batch_alter_table('authors', schema='results') as batch_op:
        batch_op.drop_index(batch_op.f('ix_results_authors_id'))
        batch_op.create_unique_constraint(batch_op.f('authors_orcid_key'), ['orcid'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('article', schema='results') as batch_op:
        batch_op.alter_column('open',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('classification_codes', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.CHAR(length=2),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)

    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.drop_constraint("public_banner_unique_id", type_='unique')
    # ### end Alembic commands ###
