# Generated by Django 4.0 on 2023-07-28 19:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exsclaim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('journal_family', models.CharField(choices=[('nature', 'nature'), ('rcs', 'rcs')], max_length=10)),
                ('maximum_scraped', models.IntegerField(null=True)),
                ('sortby', models.CharField(choices=[('relevant', 'relevant'), ('recent', 'recent')], max_length=10)),
                ('results_dir', models.TextField()),
                ('query', models.JSONField()),
                ('save_format', models.CharField(choices=[('mongo', 'mongo'), ('csv', 'csv'), ('postgres', 'postgres'), ('visualize', 'visualize'), ('boxes', 'boxes'), ('save_subfigures', 'save_subfigures')], default='postgres', max_length=20)),
                ('mongo_connection', models.TextField()),
                ('open', models.BooleanField(blank=True, null=True)),
                ('logging', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None)),
            ],
        ),
    ]
