# Generated by Django 4.0 on 2023-07-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exsclaim', '0002_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
