# Generated by Django 4.0 on 2023-07-31 18:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exsclaim', '0003_alter_query_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='query',
        ),
        migrations.AddField(
            model_name='query',
            name='synonyms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='query',
            name='term',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='results_dir',
            field=models.TextField(null=True),
        ),
    ]
