# Generated by Django 4.0 on 2023-08-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exsclaim', '0006_remove_query_logging_remove_query_mongo_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='llm',
            field=models.CharField(choices=[('vicuna', 'vicuna'), ('gpt3.5-turbo', 'gpt3.5-turbo'), ('gpt-4', 'gpt-4')], default='postgres', max_length=15),
        ),
        migrations.AddField(
            model_name='query',
            name='model_key',
            field=models.TextField(null=True),
        ),
    ]
